---

- hosts: all
  become: true
  tasks:

  - name: update apt repository
    apt: 
      update_cache: yes


  - name: install apache2_mod_proxy
    apt: 
      name: apache2
      state: latest

  - name: add PHP support for apache2
    apt:
      name: libapache2-mod-php
      state: latest