---

- hosts: all
  become: true
  tasks:

  - name: "install apache and php packages"
    package: 
      name: 
       - "{{ apache_package }}"
       - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: Enable service to start on boot up - CentOS
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Create firewall rule for apache service - CentOS
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
    when: ansible_distribution == "CentOS"