---

- hosts: all
  become: true
  tasks:

  - name: "install apache2 and php packages and update cache - Ubuntu"
    apt: 
      name: 
       - apache2
       - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: "install apache2 and php and update cache  - CentOS"
    dnf: 
      name: 
       - httpd
       - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: Enable service to start on boot up - CentOS
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Create firewall rule for apache service - CentOS
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
    when: ansible_distribution == "CentOS"