---

- hosts: all
  become: true
  tasks:
  
  - name: "install apache and php packages"
    package: 
      name: 
       - "{{ apache_package }}"
       - "{{ php_package }}"
      state: absent
      update_cache: yes

  - name: Disable HTTP for CentOS
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: disabled
    when: ansible_distribution == "CentOS"


  # - name: Stop httpd for CentOS
  #   service:
  #     name: httpd
  #     state: stopped
  #   when: ansible_distribution == "CentOS"


